# 全局 WireGuard
[Interface]
PrivateKey = 
Address = 

PostUp = ip -4 rule add from $(selfip) lookup main
PostDown = ip -4 rule delete from $(selfip) lookup main

[Peer]
# US-FREE#86
PublicKey = 
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 

PersistentKeepalive = 25
