services:
    portainer-ce:
        ports:
            - 9000:9000
        network_mode: bridge
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/portainer/data:/data
        image: portainer/portainer-ce:lts
