services:
    aria2:
        container_name: aria2
        image: superng6/aria2:a2b-latest
        network_mode: bridge
        ports:
            - 6800:6800
            - 8080:8080
        volumes:
            - /home/user/Downloads/aria2/config:/config
            - /home/user/Downloads/aria2/downloads:/downloads
            - /lib/modules:/lib/modules
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Shanghai
            - SECRET=token
            - CACHE=512M
            - PORT=6800
            - WEBUI=true
            - WEBUI_PORT=8080
            - BTPORT=32516
            - UT=true
            - QUIET=true
            - SMD=true
            - A2B=true
            - A2B_DISABLE_LOG=false
            - CRA2B=2h
        restart: unless-stopped
