services:
    openlist:
        container_name: openlist
        image: openlistteam/openlist:latest
        ports:
            - 5244:5244
        network_mode: bridge
        environment:
            - UMASK=022
            - TZ=Asia/Shanghai
        user: 1000:1000
        volumes:
            - /opt/openlist/data:/opt/openlist/data
        restart: unless-stopped
